# ---------- Build Stage ----------
FROM node:20 AS builder

WORKDIR /app

ARG REACT_APP_ENV
ARG REACT_APP_GOOGLE_MAPS_API_KEY
ARG REACT_APP_RAPIDAPI_KEY
ARG REACT_APP_OPENWEATHERMAP_API_KEY
ARG REACT_APP_GEMINI_API_KEY

ENV REACT_APP_ENV=$REACT_APP_ENV
ENV REACT_APP_GOOGLE_MAPS_API_KEY=$REACT_APP_GOOGLE_MAPS_API_KEY
ENV REACT_APP_RAPIDAPI_KEY=$REACT_APP_RAPIDAPI_KEY
ENV REACT_APP_OPENWEATHERMAP_API_KEY=$REACT_APP_OPENWEATHERMAP_API_KEY
ENV REACT_APP_GEMINI_API_KEY=$REACT_APP_GEMINI_API_KEY

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ---------- Production Stage ----------
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]